name: xpEconomy
version: "beta"
author: Nathan Klein
main: com.gmail.neklein3.master.Main
api-version: 1.17
commands:
  atmTwoWayMode:
    description: Turns on or off two way conversion on ATMs
    usage: /atmTwoWayMode <on/off>
    permission: xpEconomy.admin