name: xpEconomy
version: "beta"
author: Nathan Klein Cole Wombwell
main: com.gmail.neklein3.master.Main
api-version: 1.17
commands:
  assignBanker:
    description: Assigns a player to be the server's Banker.  Only one player can be the Banker at a time.  To clear the role of Banker, type /assignBanker clear
    usage: /assignBanker <player>
    permission: xpEconomy.assignBanker
  xpEconomySettings:
    description: Enter no arguments to display current settings
    usage: /xpEconomySettings <exchangeTerminal/ATM> <twoWayMode/creation/destruction> <on/off>
    permission: xpEconomy.settings